-- require("clipboard")
-- require("launcher")
require("hotkey")
require("omnibar")
-- Optional: Hotkey to reload Hammerspoon config (e.g., Alt + Cmd + R)
hs.hotkey.bind({ "alt", "cmd" }, "r", function()
	hs.reload()
	hs.notification.show("Hammerspoon", "", "Config Reloaded")
end)
